fix(config): correct indentation of inserted leagues (was 6 spaces, should be 4)
Fixes YAML ParserError that broke the scrape workflow:
  yaml.parser.ParserError: while parsing a block collection
  in 'config.yml', line 5, column 5
  expected <block end>, but found '<block sequence start>'
  in 'config.yml', line 40, column 7